CREATE TABLE owners (
id INTEGER PRIMARY KEY,
name VARCHAR(255)
age INTEGER,
driver_license BOOLEAN
)

ALTER TABLE owners ALTER COLUMN age SET NOT NULL,
ADD CONSTRAINT age_check CHECK (age > 18),
ALTER COLUMN name SET NOT NULL,
ALTER COLUMN driver_license SET NOT NULL


CREATE TABLE cars (
id INTEGER PRIMARY KEY,
owner_id INTEGER,
brand VARCHAR(255),
model VARCHAR(255),
price DECIMAL (100, 2)
)

ALTER TABLE cars ALTER COLUMN price SET NOT NULL,
ALTER COLUMN model SET NOT NULL,
ALTER COLUMN brand SET NOT NULL,
ADD CONSTRAINT price_check CHECK (price > 0),
ADD FOREIGN KEY (owner_id) REFERENCES owners(id)