ALTER TABLE students ADD CONSTRAINT age_check CHECK (age > 16),
ALTER COLUMN age SET DEFAULT 20,
ALTER COLUMN name SET NOT NULL,
ADD CONSTRAINT name_unique UNIQUE(NAME)

ALTER TABLE faculties ADD CONSTRAINT name_color_unique UNIQUE (name, color)
